version: '3.8'
services:
  ros-noetic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros1_noetic_dev_compose
    # Mount the workspace directory from the host into the container
    volumes:
      - ./ros1_ws:/root/ros1_ws
    # Keep stdin open and allocate a tty for interactive use
    stdin_open: true
    tty: true