db_host: "10.102.75.119"
db_port: 5432
db_name: "robot_data"
db_user: "robot_researcher"
db_password: "secret"

# Topic to Ingest
topic_name: "/scan"
topic_msg_type: "sensor_msgs/LaserScan"

# Database Target Table Name
db_table_name: "laser_scans"

# Mapping from DB Columns to ROS Message Fields
column_mapping:
  time: "header.stamp"
  frame_id: "header.frame_id"
  angle_min: "angle_min"
  angle_max: "angle_max"
  angle_increment: "angle_increment"
  time_increment: "time_increment"
  scan_time: "scan_time"
  range_min: "range_min"
  range_max: "range_max"
  # Map ROS array fields to the corresponding JSONB DB columns
  ranges: "ranges"
  intensities: "intensities"

# Batching Parameters (Optional)
# batch_size: 50 # LaserScan messages can be larger, maybe smaller batch
# flush_interval: 5.0